import time

import numpy as np
import matplotlib.pyplot as plt
from collections import deque


# This is used to remove noise from position data points generated by the beacons and the accelerometer
# A Kalman filter works by estimating the state of a dynamic system from a series of noisy measurements.
# Covariance is a measure of how much two random variables change together.
#   In the context of Kalman filters, it represents the uncertainty in the state estimate.
#   A higher covariance indicates more uncertainty, while a lower covariance indicates more confidence in the estimate.

# Constants
MARGIN_OF_ERROR = 0.1
STANDARD_DEVIATION = MARGIN_OF_ERROR / 1.96


# Define the Point class
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def get_distance_with_error(self, other):
        true_dist = ((self.x - other.x) ** 2 + (self.y - other.y) ** 2) ** 0.5
        error = np.random.normal(0, STANDARD_DEVIATION)  # Add random noise
        return true_dist + error

    def get_array(self):
        return np.array([self.x, self.y])


# Define the Extended Kalman Filter class with enhanced tuning
class ExtendedKalmanFilter:
    def __init__(self, F, Q, R, x0, P0, fixed_points):
        self.F = F  # State transition matrix
        self.Q = Q  # Process noise covariance
        self.R = R  # Measurement noise covariance
        self.x = x0  # Initial state estimate
        self.P = P0  # Initial error covariance
        self.fixed_points = fixed_points  # Fixed points for distance measurements

        # Pre-compute fixed point arrays for efficiency
        self.fixed_point_arrays = np.array([[p.x, p.y] for p in fixed_points])

    def predict(self):
        # State prediction
        self.x = self.F @ self.x
        # Covariance prediction
        self.P = self.F @ self.P @ self.F.T + self.Q

    def compute_measurement_jacobian(self):
        # Initialize H matrix with zeros
        H = np.zeros((len(self.fixed_points), len(self.x)))

        # Current state position
        x, y = self.x[0], self.x[2]

        # Calculate Jacobian entries for each fixed point
        for i, point in enumerate(self.fixed_points):
            # Distance from current estimated position to fixed point
            dx = x - point.x
            dy = y - point.y
            dist = np.sqrt(dx ** 2 + dy ** 2)

            if dist < 1e-6:  # Avoid division by zero
                dist = 1e-6

            # Derivatives of distance with respect to x, vx, y, vy
            H[i, 0] = dx / dist  # ∂d/∂x
            H[i, 1] = 0  # ∂d/∂vx = 0
            H[i, 2] = dy / dist  # ∂d/∂y
            H[i, 3] = 0  # ∂d/∂vy = 0

        return H

    def compute_expected_measurements(self):
        # Calculate expected distances based on current state
        x, y = self.x[0], self.x[2]

        # Vector of distances from current state to all fixed points
        dx = x - self.fixed_point_arrays[:, 0]
        dy = y - self.fixed_point_arrays[:, 1]
        distances = np.sqrt(dx ** 2 + dy ** 2)

        return distances

    def update(self, measurements):
        # Get measurement Jacobian at current state
        H = self.compute_measurement_jacobian()

        # Calculate expected measurements
        expected_z = self.compute_expected_measurements()

        # Innovation/residual
        y = measurements - expected_z

        # Innovation covariance
        S = H @ self.P @ H.T + self.R

        # Kalman gain - using direct computation which is safer for this case
        try:
            K = self.P @ H.T @ np.linalg.inv(S)
        except np.linalg.LinAlgError:
            # Fallback to pseudoinverse if regular inverse fails
            K = self.P @ H.T @ np.linalg.pinv(S)

        # Update state estimate
        self.x = self.x + K @ y

        # Joseph form for covariance update (more numerically stable)
        I = np.eye(len(self.x))
        self.P = (I - K @ H) @ self.P @ (I - K @ H).T + K @ self.R @ K.T

        # Ensure symmetry and positive definiteness
        self.P = (self.P + self.P.T) / 2

        # Add small value to diagonal to ensure positive definiteness
        self.P = self.P + np.eye(len(self.x)) * 1e-6


# Function to simulate the true moving point
def generate_moving_points(start_point, num_steps=50, step_size=0.1):
    points = []
    current_x, current_y = start_point

    for i in range(num_steps):
        # Linear motion along x-axis with slight noise for realism
        new_x = current_x + step_size
        new_y = current_y

        points.append(Point(new_x, new_y))

        # Update current position
        current_x, current_y = new_x, new_y

    return points


# Set up fixed reference points (keep the original three)
a = Point(292, 0)
b = Point(0, 115)
c = Point(0, 0)
fixed_points = [a, b, c]

# EKF initialization with tuned parameters
dt = 0.1  # Smaller time step for better tracking

# State transition matrix (x, vx, y, vy)
F = np.array([
    [1, dt, 0, 0],  # x = x + vx*dt
    [0, 1, 0, 0],  # vx = vx
    [0, 0, 1, dt],  # y = y + vy*dt
    [0, 0, 0, 1]  # vy = vy
])

# Process noise covariance matrix using continuous-time model
sigma_a = 0.01  # process noise due to acceleration uncertainty
G = np.array([
    [dt ** 2 / 2, 0],
    [dt, 0],
    [0, dt ** 2 / 2],
    [0, dt]
])
Q = G @ np.array([[sigma_a ** 2, 0], [0, sigma_a ** 2]]) @ G.T

# Measurement noise - slightly higher to account for distance-based errors
R = np.eye(3) * (STANDARD_DEVIATION ** 2)

# Initial state estimate - better to start slightly off than grossly wrong
# [x, vx, y, vy]
x0 = np.array([5.0, 0.1, 5.0, 0.1])  # Close to true starting position with some velocity

# Initial uncertainty - smaller values to indicate more confidence in initial state
P0 = np.diag([0.5, 0.05, 0.5, 0.05])

# Create EKF instance
ekf = ExtendedKalmanFilter(F, Q, R, x0, P0, fixed_points)

# Generate true trajectory (starting at [5, 4])
# true_points = generate_moving_points([5, 4], num_steps=100, step_size=0.05)

# Track the EKF estimates over time
MAX_HISTORY = 100  # or however many steps you want to keep
ekf_estimates = deque(maxlen=MAX_HISTORY)
innovation_history = deque(maxlen=MAX_HISTORY)
P_history = deque(maxlen=MAX_HISTORY)


def find_robot_location(da, db, dc):
    measurements = np.array([da, db, dc])
    
    # EKF predict and update steps
    ekf.predict()

    # Calculate pre-update expected measurements for innovation tracking
    expected_z = ekf.compute_expected_measurements()
    innovation = measurements - expected_z
    innovation_history.append(innovation)

    # Update step
    ekf.update(measurements)
    print(ekf.x)

    # Store current estimate and covariance
    ekf_estimates.append(np.array([ekf.x[0], ekf.x[2]]))  # [x, y]
    P_history.append(np.array([ekf.P[0, 0], ekf.P[2, 2]]))  # Position variances
    # Return the estimated position in x, y
    return ekf.x[0], ekf.x[2]
